export const ERROR = {
    HIDE_ERROR: "HIDE_ERROR",
    SHOW_ERROR: "SHOW_ERROR"
}

export const REQUEST = {
    PENDING: "REQUEST_PENDING",
    FAILED: "REQUEST_FAILED"
}

export const VALIDATE_SESSION = {
    FULFILLED: "VALIDATE_SESSION_FULFILLED"
}

export const CHART = {
    ADD_FILTER : "ADD_FILTER",
    FETCH_INITIAL_DATA_FULFILLED : "FETCH_INITIAL_DATA_FULFILLED"
}